# Generated by Django 4.1.3 on 2022-11-23 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='work_out_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 21, 37, 37, 574055)),
        ),
    ]
