# Generated by Django 4.1.3 on 2022-11-23 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_id_nro',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
    ]
