# Generated by Django 4.1.3 on 2022-11-23 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_datetime',
            field=models.TimeField(default=datetime.datetime(2022, 11, 22, 21, 37, 37, 573056)),
        ),
    ]
